### ISSUE TITLE
[BUG] Update Readme. 

### ISSUE THREAD

**Issue by NeilSayok** [DummyCo/andColorPicker#240]
**Describe the bug**
Error in Readme. Line 90 ` object : HSLColorPickerSeekBar.DefaultOnColorPickListener()`

As per your Example app/src/main/java/codes/side/andcolorpicker/app/fragment/HSLSeekBarGithubSampleFragment.kt

Line Should be : `object : OnIntegerHSLColorPickListener() `

**Comment by smelfungus** [comment]
@NeilSayok, thank you for the report!
